"""add_chats_table_and_chat_id_to_history

Revision ID: 2c60b8e332c4
Revises: 9851267b810c
Create Date: 2026-04-19 18:28:10.530955

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c60b8e332c4"
down_revision = "9851267b810c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("DELETE FROM users_history")
    op.add_column("users_history", sa.Column("chat_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_users_history_chat_id",
        "users_history",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_history", type_="foreignkey")
    op.drop_column("users_history", "chat_id")
    op.drop_table("chats")
    # ### end Alembic commands ###
