"""add users_activity table

Revision ID: 6edbb824d0da
Revises: 44757ac98ed9
Create Date: 2026-04-03 13:46:43.535672

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6edbb824d0da"
down_revision = "44757ac98ed9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("users_activity")
    # ### end Alembic commands ###
