"""make user_id not unique for user activity

Revision ID: 85620f92dbad
Revises: 6edbb824d0da
Create Date: 2026-04-04 16:20:01.415778

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "85620f92dbad"
down_revision = "6edbb824d0da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("users_activity_user_id_key"), "users_activity", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_activity_user_id_key"),
        "users_activity",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
