"""support sources in history

Revision ID: 9851267b810c
Revises: 2ffd448748c1
Create Date: 2026-04-05 13:32:17.727307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9851267b810c"
down_revision = "2ffd448748c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_history", sa.Column("context", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_history", "context")
    # ### end Alembic commands ###
