"""initial schema

Схлопнутая начальная схема (squash всех прежних миграций в одну) — вся история
пересобрана из текущих моделей `app.db.models`. Сделано в рамках API-02: сюда сразу
вписан UNIQUE(users.email) (см. `sa.UniqueConstraint('email')` в таблице users).

ВАЖНО про уже применённый alembic. Прежняя цепочка ревизий удалена, поэтому на
стендах, где alembic ранее накатывался, `alembic_version` указывает на несуществующую
ревизию и `alembic upgrade head` не может её найти.
НЕ сносите схему (`DROP SCHEMA public CASCADE`) — это стирает ВСЕ данные (пользователи,
организации, чаты, файлы, индексы). Вместо этого один раз переставьте указатель без
потери данных:  `alembic stamp --purge head`  (именно --purge: обычный stamp пытается
резолвить удалённую текущую ревизию и падает; пошагово — в ALEMBIC_RECOVERY.md).

`upgrade()` идемпотентна: если схема уже существует, функция ничего не создаёт и не
трогает данные — то есть прямой/повторный `alembic upgrade head` больше не роняет
контейнер и не является поводом «чистить» базу.

Revision ID: b6bcf27f08c6
Revises:
Create Date: 2026-07-09 20:08:10.437771

"""

from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6bcf27f08c6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Идемпотентность: на стендах, где схема уже создана прежними (удалёнными при
    # сквоше) миграциями, ничего не пересоздаём — иначе CREATE TABLE упал бы на
    # существующих таблицах и контейнер API не поднялся бы. Такие стенды переводятся
    # на эту ревизию через `alembic stamp --purge head` (см. ALEMBIC_RECOVERY.md); эта проверка —
    # защита и от прямого/повторного `alembic upgrade head`. В offline-режиме (--sql)
    # инспектора нет — генерируем полный DDL как есть.
    if not context.is_offline_mode() and sa.inspect(op.get_bind()).has_table("users"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("model_answer", sa.String(), nullable=True),
        sa.Column("is_ok", sa.Boolean(), nullable=True),
        sa.Column("corrected_answer", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("system_key", sa.String(), nullable=False),
        sa.Column("s3_url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_key"),
    )
    op.create_table(
        "indexes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vector_store_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="ready", nullable=False),
        sa.Column("file_counts", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("source_file_ids", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_organizations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "org_id"),
    )
    op.create_table(
        "users_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("count_vector", sa.Integer(), nullable=False),
        sa.Column("count_fulltext", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "users_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", name="messagerole"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_history")
    op.drop_table("users_setting")
    op.drop_table("users_activity")
    op.drop_table("user_organizations")
    op.drop_table("indexes")
    op.drop_table("files")
    op.drop_table("chats")
    op.drop_table("users")
    op.drop_table("reviews")
    op.drop_table("organizations")
    # Enum-тип создаётся неявно вместе с колонкой users_history.role, но автоматически
    # НЕ удаляется при drop_table — снимаем вручную, иначе повторный upgrade падает на
    # CREATE TYPE messagerole (тип уже существует).
    sa.Enum("user", "assistant", name="messagerole").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
